feat: fix and overhaul CGI and comment management
- Apply strict SQL quoting fix
- Add a CGI support dev server
- Change the backup naming to be namespaced (common prefix)
- Inline the seo plugin
- Add mock mail tools for cgi dev

diff --git a/src/cgi-bin/submit b/src/cgi-bin/submit
--- a/src/cgi-bin/submit
+++ b/src/cgi-bin/submit
@@ -1,7 +1,13 @@
+---
+---
 #!/bin/bash
-
 set -o pipefail
 set -o errexit
+
+ALEF_DB="${ALEF_DB:-comments.db}"
+ALEF_URL="{{ site.url }}"
+ALEF_MODERATOR="{{ site.email }}"
+ALEF_FROM="noreply@{{ site.url | remove: 'https://' | remove: 'http://' }}"
 
 echo -en "Status: 200 OK\r\n"
 echo -en "Content-type: text/plain;charset=UTF-8\r\n\r\n"
@@ -11,13 +17,9 @@ echo --
 echo User Agent: $HTTP_USER_AGENT
 echo IP Address: $REMOTE_ADDR
 echo
-echo mehdix.ir
+echo $ALEF_URL
 ' EXIT
 
-# Read $CONTENT_LENGTH bytes into POST_STRING variable.
-# This applies only to POST requests.
-# or VAR=$(cat) for multiline input
-#read POST_STRING
 POST_STRING=$(cat)
 
 # https://stackoverflow.com/a/37840948/
@@ -30,44 +32,28 @@ IFS=$saveIFS
 
 # https://stackoverflow.com/a/3919908/
 for ((i=0; i<${#parm[@]}; i+=2)) do
-	# Convert dashes to underscores and define a variable
 	varname=var_$( echo ${parm[i]} | sed s/-/_/ )
 	declare $varname="$(urldecode ${parm[i+1]})"
-	#echo "${varname}=${!varname}"
 done
 
 # Make sure mandatory fields are present
 ([ -z "$var_message" ] || [ -z "$var_name" ] || [ -z "$var_email" ]) && {
 	echo "لطفا برای ثبت دیدگاه متن و نام و ایمیل را وارد کنید."
-	echo "mehdix.ir: missing mandatory form fields." >&2
+	echo "$ALEF_URL: missing mandatory form fields." >&2
 	exit 1
 }
 
-# Make sure anti spam field is present and correct
-([ -z "$var_puzzle" ] || [ "$var_puzzle" != "$ALEF_PUZZLE" ]) && {
+# Anti-spam check (skip if ALEF_PUZZLE not configured)
+[ -n "$ALEF_PUZZLE" ] && [ "$var_puzzle" != "$ALEF_PUZZLE" ] && {
 	echo "معما رو درست حل نکردی رفیق. نمی‌شه، شرمنده."
-	echo "mehdix.ir: wrong puzzle." >&2
+	echo "$ALEF_URL: wrong puzzle." >&2
 	exit 1
 }
 
-true && [ -n "$var_reply_to" ] && {
-	#echo is a reply: $var_reply_to
-	#echo getting the email of the OP
-	op_email_query=$(cat <<-EOF
-	SELECT DISTINCT email FROM comments
-	WHERE id = "$var_reply_to" or legacy_id = "$var_reply_to";
-	EOF
-	)
-	op_email=$(sqlite3 "$ALEF_DB" "$op_email_query")
-	#echo "$op_email"
-}
-
-false && [ -n "$var_website" ] && {
-	echo has a websitie: $var_website
-}
-
-false && [ -n "$var_page_id" ] && {
-	echo has a page id: $var_page_id
+[ -n "$var_reply_to" ] && {
+	op_email=$(sqlite3 "$ALEF_DB" \
+		".param set :reply_to \"$var_reply_to\"" \
+		"SELECT DISTINCT email FROM comments WHERE id = :reply_to OR legacy_id = :reply_to")
 }
 
 # Initialize DB if not exists
@@ -98,39 +84,33 @@ CREATE TABLE IF NOT EXISTS comments (
 EOF
 }
 
-# RETURNING needs at least sqlite version 3.35.0
-INSERT_QUERY=$(cat <<-EOF
-	INSERT INTO comments
-		(time, name, email, page_id, reply_to, website, spam, message)
-	VALUES (datetime(), "$var_name", "$var_email", "$var_page_id",
-		"$var_reply_to", "$var_website", "$spam", "$var_message")
-	RETURNING ID;
-EOF
-)
-#echo ALEF_DB "$ALEF_DB"
-#echo INSERT_QUERY "$INSERT_QUERY"
-
-# If file exists and is writable
-[ -w "$ALEF_DB" ] && NEW_ID=$(sqlite3 "$ALEF_DB" "$INSERT_QUERY")
-
-#sqlite3 "$ALEF_DB" "$INSERT_QUERY"
-#echo NEW_ID "$NEW_ID"
+# If file exists and is writable (RETURNING needs sqlite >= 3.35.0)
+[ -w "$ALEF_DB" ] && NEW_ID=$(sqlite3 "$ALEF_DB" \
+	".param set :name \"$var_name\"" \
+	".param set :email \"$var_email\"" \
+	".param set :page_id \"$var_page_id\"" \
+	".param set :reply_to \"$var_reply_to\"" \
+	".param set :website \"$var_website\"" \
+	".param set :spam \"$spam\"" \
+	".param set :message \"$var_message\"" \
+	"INSERT INTO comments (time, name, email, page_id, reply_to, website, spam, message)
+	 VALUES (datetime(), :name, :email, :page_id, :reply_to, :website, :spam, :message)
+	 RETURNING id")
 
 # Report success
 echo دیدگاهت ثبت شد و با اولین بیلد وبسایت منتشر خواهد شد.
 
-sub="https://mehdix.ir/$var_page_id.html#$NEW_ID"
+sub="${ALEF_URL}/$var_page_id.html#$NEW_ID"
 
 # Convert internationalized header to RFC2047 format
 from_author="$(mailutils flt2047 --charset=utf-8 'کامنتدونی')"
-from_header="From: $from_author <noreply@mehdix.ir>"
+from_header="From: $from_author <${ALEF_FROM}>"
 
 # mail is from mailutils package
-#Inform the author about the new comment
-cat <<EOF | mail mehdi@mehdix.org -s "دیدگاه جدید" \
+[ -n "$ALEF_MODERATOR" ] && cat <<EOF | mail "$ALEF_MODERATOR" -s "دیدگاه جدید" \
 	-a "$from_header" \
 	-a "Content-Type: text/plain; charset=UTF-8"
-${var_name} به دیدگاهت رو سایت مهدیکس جواب داد:
+${var_name} دیدگاه جدید گذاشت:
 
 	$var_message
 
@@ -140,11 +120,10 @@ ${sub}
 کامنتدونی
 EOF
 
-#Inform the OP about the new comment
 [ -n "$op_email" ] && cat <<EOF | mail "$op_email" -s "دیدگاه جدید" \
 	-a "$from_header" \
 	-a "Content-Type: text/plain; charset=UTF-8"
-${var_name} به دیدگاهت رو سایت مهدیکس جواب داد:
+${var_name} به دیدگاهت جواب داد:
 
 	$var_message
 
